import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  flexRow: {flexDirection: 'row'},
  flexShrinkOne: {flexShrink: 1},
  flexOne: {flex: 1},
  container: {
    flex: 1,
    paddingVertical: 16,
    backgroundColor: '#f5f5f5',
  },
  userCard: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#fff',
    padding: 16,
    marginHorizontal: 10,
    marginVertical: 8,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginRight: 16,
    alignSelf: 'center',
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  userName: {
    fontSize: 14,
  },
  userDetail: {
    fontSize: 14,
    color: '#666',
  },
  userDetailWithHeighlight: {backgroundColor: '#e04f4f', color: 'white'},
  buttonDark: {
    backgroundColor: '#1f468f',
    paddingVertical: 12,
    borderRadius: 10,
    marginTop: 10,
    width: '50%',
    justifyContent: 'flex-start',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  buttonLight: {
    backgroundColor: '#5d87d4',
  },
  buttonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  meetButton: {
    backgroundColor: '#1f468f',
    paddingVertical: 12,
    borderRadius: 10,
    marginTop: 10,
    justifyContent: 'flex-start',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
    width: '30%',
  },

  headingTitle: {flexDirection: 'row', justifyContent: 'space-around'},
  headingTitleText: {alignSelf: 'center', fontSize: 15, fontWeight: 'bold'},
  listHeading: {marginLeft: 15},
  listHeadingText: {fontSize: 15, fontWeight: 'bold', marginBottom: 10},
  epmtyListMsg: {
    fontSize: 15,
    fontWeight: '500',
    marginBottom: 10,
    textAlign: 'center',
  },
  emptyContainer: {flex: 1, justifyContent: 'flex-start', alignItems: 'center'},
});
